### ISSUE TITLE
Not worked on Ubuntu 14.04

### ISSUE THREAD

**Issue by kpaxqin** [caolvchong/mock-api#2]
Got this error on Ubuntu 14.04:
/usr/bin/env node --harmony : no such file 
I can run `node -v` or  `node --harmony` properly in my terminal.

I've tried some ways and found that change the first line in shell.js to
```
#!/usr/bin/node --harmony
```
will solve the problem.

**Comment by caolvchong** [comment]
see: https://github.com/joyent/node/issues/3911
